py_binary(
   name="helloworld",
   srcs=["hello_world.py"],
   main="hello_world.py",
)

py_binary(
   name="deep_thought",
   srcs=["deep_thought.py"],
   main="deep_thought.py",
   visibility=[":__subpackages__"],
)
